/**
 * Differential Model — Stage 26
 *
 * Computes traction efficiency and yaw moment contribution from different
 * differential types: open, LSD (limited-slip), and locked.
 *
 * Reference: Milliken & Milliken, Race Car Vehicle Dynamics Ch.22 (differential analysis)
 * Heisler, Vehicle and Engine Technology (LSD torque bias ratios)
 */

export type DiffType = 'open' | 'lsd' | 'locked';

const G = 9.81;

interface DiffInput {
  mass:                 number;   // kg
  peakMu:               number;   // tyre peak friction coefficient
  cgHeight:             number;   // m
  trackWidth:           number;   // m
  frontWeightFraction:  number;
  drivetrainType:       string;   // 'FWD' | 'RWD' | 'AWD' | 'AWD_TV'
  diffType:             DiffType;
  lsdLockingPercent:    number;   // 0–100
}

/**
 * Traction efficiency factor (0.5–1.0) for the driven axle.
 * Multiply driveForce by this to get actual available traction.
 */
export function diffTractionFactor(inp: DiffInput): number {
  const { mass, peakMu, cgHeight, trackWidth, frontWeightFraction, drivetrainType } = inp;

  // Axle normal load (static, no aero for simplicity — conservative)
  const rearFrac  = 1 - frontWeightFraction;
  let FzAxle: number;
  if (drivetrainType === 'FWD') {
    FzAxle = mass * G * frontWeightFraction;
  } else if (drivetrainType === 'RWD') {
    FzAxle = mass * G * rearFrac;
  } else {
    // AWD: weight both axles (rear dominant for typical AWD)
    FzAxle = mass * G * (0.6 * rearFrac + 0.4 * frontWeightFraction);
  }

  // Representative lateral load transfer at 70% of peak cornering
  const ΔFz = Math.min(FzAxle * 0.45, mass * peakMu * 0.7 * G * cgHeight / trackWidth);

  // Traction efficiency relative to locked
  const κ = (inp.lsdLockingPercent ?? 0) / 100;
  let η: number;
  switch (inp.diffType) {
    case 'locked': η = 1.0;                              break;
    case 'lsd':    η = 1 - 2 * ΔFz * (1 - κ) / FzAxle; break;
    case 'open':
    default:       η = 1 - 2 * ΔFz / FzAxle;            break;
  }
  return Math.max(0.50, Math.min(1.0, η));
}

/**
 * Yaw moment [Nm] generated by differential torque imbalance during cornering.
 * Positive = oversteer tendency (rear diff helping rotation).
 * Negative = understeer tendency (front diff fighting rotation).
 */
export function diffYawMoment(inp: DiffInput): number {
  const { mass, peakMu, cgHeight, trackWidth, frontWeightFraction, drivetrainType } = inp;

  const rearFrac = 1 - frontWeightFraction;
  const FzAxle = drivetrainType === 'FWD'
    ? mass * G * frontWeightFraction
    : mass * G * rearFrac;

  const ΔFz = Math.min(FzAxle * 0.45, mass * peakMu * 0.7 * G * cgHeight / trackWidth);
  const κ = (inp.lsdLockingPercent ?? 0) / 100;

  // Yaw moment from torque imbalance
  const M_diff = κ * peakMu * ΔFz * trackWidth;

  // Sign: rear diff → positive (rotation assist); front diff → negative (understeer)
  return drivetrainType === 'FWD' ? -M_diff : M_diff;
}
