import type { PhysicsResult, PacejkaResult } from '../physics/types';
import { InfoTooltip } from './InfoTooltip';
import './ResultsPanel.css';

interface Props {
  result:   PhysicsResult;
  pacejka?: PacejkaResult;
}

const BALANCE_CONFIG = {
  understeer: { label: 'UNDERSTEER', color: '#f97316' },
  neutral:    { label: 'NEUTRAL',    color: '#4ade80' },
  oversteer:  { label: 'OVERSTEER',  color: '#f43f5e' },
};

interface MetricProps {
  label:     string;
  value:     string;
  sub?:      string;
  highlight?: boolean;
  tip:       string;
}

function Metric({ label, value, sub, highlight, tip }: MetricProps) {
  return (
    <div className={`metric ${highlight ? 'metric--highlight' : ''}`}>
      <div className="metric-value">{value}</div>
      {sub && <div className="metric-sub">{sub}</div>}
      <div className="metric-label">
        {label}
        <InfoTooltip text={tip} />
      </div>
    </div>
  );
}

export function ResultsPanel({ result, pacejka }: Props) {
  const bc    = BALANCE_CONFIG[result.balance];
  const kSign = result.underSteerGradientDegPerG >= 0 ? '+' : '';

  const LINEAR_LIMIT_DEG = 5;
  const modelWarning =
    result.frontSlipAngleDeg > LINEAR_LIMIT_DEG ||
    result.rearSlipAngleDeg  > LINEAR_LIMIT_DEG;

  return (
    <div className="results-panel">

      {modelWarning && (
        <div className="model-warning">
          ⚠ Slip angles exceed ~5° — linear model out of range. Results indicative only. See Pacejka charts below for accurate forces.
        </div>
      )}

      <div
        className="balance-badge"
        style={{ borderColor: bc.color, color: bc.color }}
        title="Whether the front or rear axle is generating more slip angle. Understeer = front slips more. Oversteer = rear slips more."
      >
        {bc.label}
        <span className="balance-diff">
          {result.slipAngleDiffDeg >= 0 ? '+' : ''}
          {result.slipAngleDiffDeg.toFixed(2)}° (αf − αr)
        </span>
      </div>

      <div className="metrics-grid">
        <Metric
          label="Lat. acceleration"
          value={result.lateralAccelerationG.toFixed(3)}
          sub="g"
          tip="Centripetal acceleration in the corner = V²/R divided by g. At 1g the car is at the grip limit of a typical road tyre. This drives all lateral tyre forces."
        />
        <Metric
          label="Understeer gradient K"
          value={`${kSign}${result.underSteerGradientDegPerG.toFixed(2)}`}
          sub="deg/g"
          highlight={Math.abs(result.underSteerGradientDegPerG) > 2}
          tip="Extra steering angle the driver must add per g of lateral acceleration. K > 0 = understeer (more steer needed as speed rises). K < 0 = oversteer (less steer needed; car becomes unstable above critical speed). K = 0 = neutral steer."
        />
        <Metric
          label="Front slip αf"
          value={result.frontSlipAngleDeg.toFixed(3)}
          sub="deg"
          tip="Angle between the front tyre's velocity direction and its heading. The tyre builds lateral force as α increases. Linear model valid up to ~5°; above that Pacejka is needed."
        />
        <Metric
          label="Rear slip αr"
          value={result.rearSlipAngleDeg.toFixed(3)}
          sub="deg"
          tip="Angle between the rear tyre's velocity direction and its heading. If αr > αf the rear is working harder = oversteer tendency. If αf > αr = understeer."
        />
        <Metric
          label="Steer — kinematic"
          value={result.kinematicSteerAngleDeg.toFixed(3)}
          sub="deg (L/R)"
          tip="Pure geometry steer angle to follow this arc at zero speed — Ackermann steer angle. = wheelbase ÷ radius (in radians). Independent of speed and tyre properties."
        />
        <Metric
          label="Dynamic correction"
          value={`${result.dynamicCorrectionDeg >= 0 ? '+' : ''}${result.dynamicCorrectionDeg.toFixed(3)}`}
          sub="deg (K·ay)"
          tip="Extra steer beyond the geometric angle needed to balance tyre slip. = K × ay. Positive = driver adds steer (understeer). Negative = driver removes steer (oversteer)."
        />
        <Metric
          label="Total steer δ"
          value={result.totalSteerAngleDeg.toFixed(3)}
          sub="deg"
          tip="Total steering input = kinematic + dynamic correction. This is the tyre steer angle. Divide by the steering ratio to get steering wheel angle."
        />
        <Metric
          label="Yaw rate"
          value={(result.yawRateRadPerS * 180 / Math.PI).toFixed(1)}
          sub="deg/s"
          tip="How fast the car rotates about its vertical axis. r = V/R. A higher speed or tighter corner = higher yaw rate. Important for stability control systems."
        />
      </div>

      <div className="forces-row">
        <div className="force-item">
          <span className="force-label">
            Front Fy
            <InfoTooltip text="Lateral force generated by the front axle (both tyres combined). Computed from moment equilibrium: Fyf = m·ay·b/L. This is what the front tyres must generate to keep the car on the arc." />
          </span>
          <span className="force-value">{(result.frontLateralForceN / 1000).toFixed(3)} kN</span>
        </div>
        <div className="force-item">
          <span className="force-label">
            Rear Fy
            <InfoTooltip text="Lateral force generated by the rear axle (both tyres combined). Fyr = m·ay·a/L. The front/rear split depends on CG position (a and b)." />
          </span>
          <span className="force-value">{(result.rearLateralForceN / 1000).toFixed(3)} kN</span>
        </div>
      </div>

      {/* ── Stage 3: Load transfer + drivetrain ────────────────────────── */}
      {pacejka && <Stage3Panel p={pacejka} />}

    </div>
  );
}

// ── Stage 3 panel ─────────────────────────────────────────────────────────────

function UtilBar({ label, pct, color }: { label: string; pct: number; color: string }) {
  return (
    <div style={{ flex: 1 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 9, marginBottom: 3 }}>
        <span style={{ color: '#5a5a7a' }}>{label}</span>
        <span style={{ color, fontWeight: 600, fontVariantNumeric: 'tabular-nums' }}>{(pct * 100).toFixed(0)}%</span>
      </div>
      <div style={{ height: 4, background: '#1e1e2e', borderRadius: 2, overflow: 'hidden' }}>
        <div style={{ height: '100%', width: `${Math.min(pct * 100, 100)}%`, background: color, borderRadius: 2, transition: 'width 0.1s' }} />
      </div>
    </div>
  );
}

function CornerLoad({ label, fz }: { label: string; fz: number }) {
  return (
    <div style={{ textAlign: 'center' }}>
      <div style={{ fontSize: 9, color: '#4a4a6a', marginBottom: 2 }}>{label}</div>
      <div style={{ fontSize: 11, fontWeight: 600, color: '#c0c0e0', fontVariantNumeric: 'tabular-nums' }}>
        {(fz / 1000).toFixed(2)}
      </div>
      <div style={{ fontSize: 8, color: '#3a3a5a' }}>kN</div>
    </div>
  );
}

function Stage3Panel({ p }: { p: PacejkaResult }) {
  const hasFx = p.FxFront > 1 || p.FxRear > 1;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ fontSize: 10, fontWeight: 600, color: '#4a4a6a', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
        Stage 3 — Load Transfer &amp; Drivetrain
      </div>
      <div>
        <div style={{ fontSize: 9, color: '#4a4a6a', marginBottom: 6 }}>
          Per-corner loads
          <InfoTooltip text="Normal force Fz on each tyre after lateral + longitudinal load transfer. Outside tyres gain load in cornering. Unequal Fz changes the Pacejka curve per tyre → real grip loss captured." />
        </div>
        <div style={{ background: '#0c0c14', border: '1px solid #1e1e2e', borderRadius: 6, padding: '8px 12px' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px 16px' }}>
            <CornerLoad label="FL (inside)"  fz={p.FzFL} />
            <CornerLoad label="FR (outside)" fz={p.FzFR} />
            <CornerLoad label="RL (inside)"  fz={p.FzRL} />
            <CornerLoad label="RR (outside)" fz={p.FzRR} />
          </div>
          <div style={{ marginTop: 6, paddingTop: 6, borderTop: '1px solid #1e1e2e', display: 'flex', gap: 12, fontSize: 9, color: '#4a4a6a', flexWrap: 'wrap' }}>
            <span>Lat ΔFz F: <b style={{ color: '#c0c0e0' }}>{(p.latTransferFront / 1000).toFixed(2)} kN</b></span>
            <span>Lat ΔFz R: <b style={{ color: '#c0c0e0' }}>{(p.latTransferRear / 1000).toFixed(2)} kN</b></span>
            {p.longTransfer > 10 && <span>Long ΔFz: <b style={{ color: '#c0c0e0' }}>{(p.longTransfer / 1000).toFixed(2)} kN</b></span>}
          </div>
        </div>
      </div>
      <div>
        <div style={{ fontSize: 9, color: '#4a4a6a', marginBottom: 6 }}>
          Friction circle utilisation
          <InfoTooltip text="Front/rear tyre grip usage. Lateral: Fy/(μ·Fz). Combined: √(Fy²+Fx²)/(μ·Fz) — shows how throttle on driven wheels eats into cornering grip." />
        </div>
        <div style={{ background: '#0c0c14', border: '1px solid #1e1e2e', borderRadius: 6, padding: '8px 12px', display: 'flex', flexDirection: 'column', gap: 6 }}>
          <UtilBar label="Front lateral" pct={p.frontUtilisation} color="#60a5fa" />
          <UtilBar label="Rear  lateral" pct={p.rearUtilisation}  color="#f87171" />
          {hasFx && <>
            <UtilBar label="Front combined" pct={p.frontCombinedUtil} color="#a78bfa" />
            <UtilBar label="Rear  combined" pct={p.rearCombinedUtil}  color="#f97316" />
          </>}
        </div>
      </div>
      {hasFx && (
        <div style={{ background: '#0c0c14', border: '1px solid #1e1e2e', borderRadius: 6, padding: '8px 12px', display: 'flex', flexDirection: 'column', gap: 4 }}>
          <div style={{ fontSize: 9, color: '#4a4a6a', marginBottom: 2, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em' }}>Drivetrain</div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10 }}>
            <span style={{ color: '#4a4a6a' }}>Drive force</span>
            <span style={{ color: '#c0c0e0', fontVariantNumeric: 'tabular-nums' }}>{(p.driveForceN / 1000).toFixed(2)} kN</span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10 }}>
            <span style={{ color: '#4a4a6a' }}>Fx front / rear</span>
            <span style={{ color: '#c0c0e0', fontVariantNumeric: 'tabular-nums' }}>{(p.FxFront / 1000).toFixed(2)} / {(p.FxRear / 1000).toFixed(2)} kN</span>
          </div>
          {p.tvYawMoment !== 0 && (
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10, borderTop: '1px solid #1e1e2e', paddingTop: 4, marginTop: 2 }}>
              <span style={{ color: '#4a4a6a' }}>TV yaw moment <InfoTooltip text="Torque-vectoring yaw moment = FxRear × tvBias × TW/2. Positive = helps car rotate = reduces understeer. Control law: tvBias ∝ (αf−αr)." /></span>
              <span style={{ color: p.tvYawMoment > 0 ? '#4ade80' : '#f43f5e', fontVariantNumeric: 'tabular-nums', fontWeight: 600 }}>{p.tvYawMoment.toFixed(0)} Nm</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
